### PR TITLE
chore: update dependencies

### LINKED ISSUE #61: Unknown binaryTarget debian-openssl-3.0.x
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

create new project
```sh
npm i
npm run setup
```
results in:

```
> setup
> prisma migrate dev && prisma db seed

Error: Unknown binaryTarget debian-openssl-3.0.x and no custom binaries were provided
```

on systems with openssl-3.0.x

### Expected Behavior

expect the setup to work on systems with openssl-3.0.x

### Actual Behavior

prisma crashes

### LINKED ISSUE #75: TypeError: interceptors.createInterceptor is not a function
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Run `npx create-remix --template remix-run/blues-stack`
(say Yes to everything)

Then run `npm run validate`, and you will see:

```sh
TypeError: interceptors.createInterceptor is not a function
    at setupServer (/Users/usr/src/my-remix-app/node_modules/msw/node/lib/index.js:8143:42)
    at mocks/index.js (/Users/usr/src/my-remix-app/mocks/index.js:3:16)
    at __require (/Users/usr/src/my-remix-app/server/index.js:12:50)
    at Object.<anonymous> (/Users/usr/src/my-remix-app/server.ts:5:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

Or, run `npm run dev` and go to `http://localhost:3000` and you will see the same error

### Expected Behavior

The template should work out of the box

### Actual Behavior

The template is broken and unusable

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #61
Closes #75

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Can't update `vitest` to `0.12.x` because of https://github.com/vitest-dev/vitest/issues/1286

**Review by mcansh — APPROVED** [review]
